// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/moolab-logos/ApexFin.tsx": () => import("../components/mockups/moolab-logos/ApexFin.tsx"),
  "./components/mockups/moolab-logos/BullHorns.tsx": () => import("../components/mockups/moolab-logos/BullHorns.tsx"),
  "./components/mockups/moolab-logos/CrownTeeth.tsx": () => import("../components/mockups/moolab-logos/CrownTeeth.tsx"),
  "./components/mockups/moolab-logos/InterlockingFangs.tsx": () => import("../components/mockups/moolab-logos/InterlockingFangs.tsx"),
  "./components/mockups/moolab-logos/JawBiteM.tsx": () => import("../components/mockups/moolab-logos/JawBiteM.tsx"),
  "./components/mockups/moolab-logos/Monogram.tsx": () => import("../components/mockups/moolab-logos/Monogram.tsx"),
  "./components/mockups/moolab-logos/RazorM.tsx": () => import("../components/mockups/moolab-logos/RazorM.tsx"),
  "./components/mockups/moolab-logos/SharkTooth.tsx": () => import("../components/mockups/moolab-logos/SharkTooth.tsx"),
  "./components/mockups/moolab-logos/ShieldCrest.tsx": () => import("../components/mockups/moolab-logos/ShieldCrest.tsx"),
  "./components/mockups/moolab-logos/TripleFang.tsx": () => import("../components/mockups/moolab-logos/TripleFang.tsx"),
  "./components/mockups/onboard-palettes/MintFresh.tsx": () => import("../components/mockups/onboard-palettes/MintFresh.tsx"),
  "./components/mockups/onboard-palettes/OceanBreeze.tsx": () => import("../components/mockups/onboard-palettes/OceanBreeze.tsx"),
  "./components/mockups/onboard-palettes/RoyalPurple.tsx": () => import("../components/mockups/onboard-palettes/RoyalPurple.tsx"),
  "./components/mockups/onboard-palettes/SunsetGlow.tsx": () => import("../components/mockups/onboard-palettes/SunsetGlow.tsx")
};
