// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onboard-palettes/MintFresh.tsx": () => import("../components/mockups/onboard-palettes/MintFresh.tsx"),
  "./components/mockups/onboard-palettes/OceanBreeze.tsx": () => import("../components/mockups/onboard-palettes/OceanBreeze.tsx"),
  "./components/mockups/onboard-palettes/RoyalPurple.tsx": () => import("../components/mockups/onboard-palettes/RoyalPurple.tsx"),
  "./components/mockups/onboard-palettes/SunsetGlow.tsx": () => import("../components/mockups/onboard-palettes/SunsetGlow.tsx")
};
