// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/moolab-logos/ApexFin.tsx": () => import("../components/mockups/moolab-logos/ApexFin.tsx"),
  "./components/mockups/moolab-logos/BullHorns.tsx": () => import("../components/mockups/moolab-logos/BullHorns.tsx"),
  "./components/mockups/moolab-logos/CrownTeeth.tsx": () => import("../components/mockups/moolab-logos/CrownTeeth.tsx"),
  "./components/mockups/moolab-logos/InterlockingFangs.tsx": () => import("../components/mockups/moolab-logos/InterlockingFangs.tsx"),
  "./components/mockups/moolab-logos/JawBiteM.tsx": () => import("../components/mockups/moolab-logos/JawBiteM.tsx"),
  "./components/mockups/moolab-logos/Monogram.tsx": () => import("../components/mockups/moolab-logos/Monogram.tsx"),
  "./components/mockups/moolab-logos/RazorM.tsx": () => import("../components/mockups/moolab-logos/RazorM.tsx"),
  "./components/mockups/moolab-logos/SharkFace1.tsx": () => import("../components/mockups/moolab-logos/SharkFace1.tsx"),
  "./components/mockups/moolab-logos/SharkFace2.tsx": () => import("../components/mockups/moolab-logos/SharkFace2.tsx"),
  "./components/mockups/moolab-logos/SharkFace3.tsx": () => import("../components/mockups/moolab-logos/SharkFace3.tsx"),
  "./components/mockups/moolab-logos/SharkFace4.tsx": () => import("../components/mockups/moolab-logos/SharkFace4.tsx"),
  "./components/mockups/moolab-logos/SharkFace5.tsx": () => import("../components/mockups/moolab-logos/SharkFace5.tsx"),
  "./components/mockups/moolab-logos/SharkM1.tsx": () => import("../components/mockups/moolab-logos/SharkM1.tsx"),
  "./components/mockups/moolab-logos/SharkM2.tsx": () => import("../components/mockups/moolab-logos/SharkM2.tsx"),
  "./components/mockups/moolab-logos/SharkM3.tsx": () => import("../components/mockups/moolab-logos/SharkM3.tsx"),
  "./components/mockups/moolab-logos/SharkM4.tsx": () => import("../components/mockups/moolab-logos/SharkM4.tsx"),
  "./components/mockups/moolab-logos/SharkM5.tsx": () => import("../components/mockups/moolab-logos/SharkM5.tsx"),
  "./components/mockups/moolab-logos/SharkTooth.tsx": () => import("../components/mockups/moolab-logos/SharkTooth.tsx"),
  "./components/mockups/moolab-logos/ShieldCrest.tsx": () => import("../components/mockups/moolab-logos/ShieldCrest.tsx"),
  "./components/mockups/moolab-logos/TripleFang.tsx": () => import("../components/mockups/moolab-logos/TripleFang.tsx"),
  "./components/mockups/onboard-palettes/MintFresh.tsx": () => import("../components/mockups/onboard-palettes/MintFresh.tsx"),
  "./components/mockups/onboard-palettes/OceanBreeze.tsx": () => import("../components/mockups/onboard-palettes/OceanBreeze.tsx"),
  "./components/mockups/onboard-palettes/RoyalPurple.tsx": () => import("../components/mockups/onboard-palettes/RoyalPurple.tsx"),
  "./components/mockups/onboard-palettes/SunsetGlow.tsx": () => import("../components/mockups/onboard-palettes/SunsetGlow.tsx")
};
